### ISSUE TITLE
count(case_number) returning 0

### ISSUE THREAD

**Issue by ledsole** [mariuspopovici/COVID-19-FL#1]
Is that accurate?  The other charts show an increase, but the the "New Cases (Last 24 hours)" remains at 0.  How often does it poll for data?

**Comment by mariuspopovici** [comment]
Hi, I will update the README to reflect recent changes. 

Unfortunately the state stopped publishing case by case data last week so did not update this until two days ago. 

They started publishing individual case data beginning Friday as a PDF report. I had to switch from a web scraping approach to extracting data out of the PDF to a CSV and processing it that way. I'm looking at automating the entire process but for now the PDF 2 CSV extract is done manually.. takes me about 5 minutes to do twice a day :)

The dashboard should now show up to date data (I update once or 2x a day) and I also started compiling the info at https://www.covid19florida.info/

**Comment by mariuspopovici** [comment]
Now updating in real time using the ArcGIS REST API.
